### PR TITLE
R Language verions of FizzBuzz

### PR DESCRIPTION
**Pull request by jcoleson**
Added version of FizzBuzz in the R language using standard R practices.

### CODE REVIEW

**Comment by virejdasani** [comment]
Hi @jcoleson, Thanks a lot for contributing!
I have never used the R language and am hugely unfamiliar with it. Before I merge, when checking if your code works, I ran the program in this online compiler and it's giving this error. Can you check it out, fix it and make another commit, thanks again!
Screenshot 2021-07-14 at 7 59 40 PM

**Comment by jcoleson** [comment]
Hi @virejdasani. can you give me the link to the online compiler you are using? 
Did it allow you to enter a value? If so what was it?
That error means the value returned by the readline function wasn't a valid number. For readability, and trying to match the other example languages, I didn't add any user input validation.
I was using R Studio when I tested it.

**Comment by virejdasani** [comment]
@jcoleson, I used [this](https://www.tutorialspoint.com/execute_r_online.php) website
and just pasted this code in the text editor on the site:
```
fizz_buzz <- function(number){
  if(number %% 3 == 0 & number %% 5 == 0) {
    print('FizzBuzz')
  }
  else if(number %% 3 == 0) {
    print('Fizz')
  }
  else if (number %% 5 == 0){
    print('Buzz')
  }
  else {
    print(number)
  }
}

# Get stop value from user
user_input <- as.integer(readline(prompt="Enter how far to go for FizzBuzz: "))

# Generate a sequence from 1 to the user's entered number
sequence_one_to_user_input <- seq(from = 1, to = user_input, by = 1)

# Pass each element in the sequence to the function, in order. 
#   (apply functions are preferred in R over for loops)
sapply(sequence_one_to_user_input, fizz_buzz)


```

**Comment by virejdasani** [comment]
I also used 2 other websites to check it and they all gave the same error

**Comment by jcoleson** [comment]
I added a commit with a check for interactive mode. The readline function only works in interactive mode and it looks like none of the online compilers run in interactive mode. 
I hard-coded 100 when it's not running in interactive mode. I think that's the best we can do. I don't know of a way to get user input when it's not running in interactive mode. I'm surprised the online compilers aren't running in interactive mode, but I assume there is some limitation I'm not aware of that keeps them from doing so.

**Comment by virejdasani** [comment]
This looks good, thanks for contributing! Going ahead with the merge. Also, if you haven't already, a star to the repo is very much appreciated!

**Pull request merged**
