### PR TITLE
add bash implementation

### PR DESCRIPTION
**Pull request by premek**

### CODE REVIEW

**Comment by virejdasani** [comment]
Hi, didn't you already send a pull request with the bash implementation: https://github.com/virejdasani/FizzBuzz-EVERYTHING/pull/17

**Comment by virejdasani** [comment]
Was this a mistake or.. ?

**Comment by virejdasani** [comment]
I will close this request in 24 hours unless you tell me otherwise.

**Comment by premek** [comment]
yeah, sorry it was supposed to be two PRs but was in one by mistake, closing this one

**Pull request closed without merging**
