### PR TITLE
Add fizzbuzz_v2.py

### PR DESCRIPTION
**Pull request by radualexandrub**
Create an alternative FizzBuzz solution in Python

### CODE REVIEW

**Comment by virejdasani** [comment]
Hi @radualexandrub, thanks for contributing! I see that there is no way to enter user input for how far to go for FizzBuzz. You have made it static at 18. Change this and I will go ahead with the merge 👍

**Comment by virejdasani** [comment]
I would also appreciate it if you could star this repo as it helps us get more contributors. Thanks in advance!

**Comment by radualexandrub** [comment]
Hello, you need to enable edit mode on Pull Requests. Refer to [docs page](https://docs.github.com/en/free-pro-team@latest/github/collaborating-with-issues-and-pull-requests/allowing-changes-to-a-pull-request-branch-created-from-a-fork).

**Comment by virejdasani** [comment]
For some reason, I am able to edit everyone else's pull requests but not yours. I am also not seeing any option to enable edit mode on this page as per the docs. Why don't you just edit the python document by allowing user input to be the max it goes on for FizzBuzz.

**Comment by virejdasani** [comment]
Have you first forked this repo? Because it says you want to merge 1 commit from an unknown repo.

**Pull request merged**
