### PR TITLE
Added New languages

### PR DESCRIPTION
**Pull request by dillir07**
Added new languages

### CODE REVIEW

**Comment by virejdasani** [comment]
Hi, thanks for the contribution, I was wondering why you have added a .js file inside the typescript folder. Is this on purpose or a mistake? Everything else looks great!

**Comment by virejdasani** [comment]
Lastly, could you set the limit as 100 instead of 10.
I will go ahead with the merge after this and you officially be a contributor 👍

**Comment by dillir07** [comment]
Hi, TypeScript is a superset of JavaScript, it adds type support to JavaScript. When we run a TypeScript file it produces JavaScript as output. That's why I kept the .js file which is the output of .ts file.

Added a readme as well.

**Comment by virejdasani** [comment]
Thanks for letting me know, I appreciate it. I'm gonna go ahead with the merge. If possible, could you star the repo, as it helps us get more contributors? Thanks in advance!

**Pull request merged**
