### PR TITLE
Mips Implementation 

### PR DESCRIPTION
**Pull request by Mystic-Developer**
Created a Mips implementation of FizzBuzz

### CODE REVIEW

**Comment by virejdasani** [comment]
Is this code running without any errors for you? Because I don't know Mips and I got errors in an online compiler.
Is the same true for you?

**Comment by Mystic-Developer** [comment]
No its running fine for me. Heres a screenshot showing the output works

Screenshot 2020-12-02 101410

**Comment by Mystic-Developer** [comment]
do you have the link to the compiler you tested it on? If so please send so I can take a look.

**Comment by Mystic-Developer** [comment]
I was able to find an online compiler for Mips and it seems to run perfectly here also. Here is a screenshot.
image

**Comment by virejdasani** [comment]
Ok, looks great. Thanks for contributing! Feel free to add more languages👍

**Pull request merged**
